name: CI workflow
on:
  issues:
    types: [opened]

jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run my own composite action
        id: my-action
        uses: ./
        with:
          who-to-greet: '@ramchipy'
      - name: Output the answer
        run: echo "The answer is ${{ steps.my-action.outputs.answer }}"